version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:v1.34.1
    ports:
      - "3000:3000"
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
