version: '3.9'

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:v0.2.1
    ports:
      - "8051:8051"
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'visualizer'
    env_file:
      -  ../envs/common-visualizer.env
